export const articles = [
  {
      title: "NVIDIA's H200 AI Chip Launch: A Game-Changer for Enterprise AI",
      date: "2024-03-19",
      category: "Hardware",
      description: "NVIDIA's latest H200 AI accelerator sets new performance records, promising up to 90% better performance than its predecessor. The chip's launch coincides with NVIDIA's stock reaching new all-time highs, reflecting the market's confidence in AI hardware.",
      technologies: ["NVIDIA", "AI Hardware", "Enterprise Computing"],
      readTime: "5 min",
      link: "https://nvidia.com/blog/h200-announcement",
      featured: true,
  },
  {
      title: "Microsoft's Semantic Kernel: Building AI-Native Applications",
      date: "2024-03-15",
      category: "Development",
      description: "An exploration of Microsoft's Semantic Kernel framework and how it's revolutionizing AI application development. Learn about orchestrating LLMs and traditional code in a unified development experience.",
      technologies: ["Semantic Kernel", ".NET", "AI Development", "Microsoft"],
      readTime: "8 min",
      link: "https://learn.microsoft.com/semantic-kernel",
      featured: true,
  },
  {
      title: "Top 10 Portfolio Website Ideas for Freelancers in 2024",
      date: "2024-03-12",
      category: "Freelancing",
      description: "Explore creative portfolio website ideas to showcase your skills as a freelancer. Learn tips for design, content, and features that attract clients and make your site stand out.",
      technologies: ["HTML", "CSS", "JavaScript", "React", "Web Design"],
      readTime: "6 min",
      link: "https://www.example.com/portfolio-website-ideas",
  },
  {
      title: "How Much Does It Cost to Build a Website in 2024?",
      date: "2024-03-11",
      category: "Business",
      description: "Breaking down the costs of building a website, from domain and hosting to design and development. Learn how to budget for your project and avoid unnecessary expenses.",
      technologies: ["WordPress", "Wix", "Web Development", "Hosting"],
      readTime: "7 min",
      link: "https://www.example.com/website-cost-guide",
  },
  {
      title: "Why Every Freelancer Needs a Personal Website",
      date: "2024-03-08",
      category: "Freelancing",
      description: "A personal website is your digital business card. Discover the benefits of having your own site to attract clients, showcase projects, and build your brand.",
      technologies: ["Web Development", "Branding", "Freelancing"],
      readTime: "5 min",
      link: "https://www.example.com/freelancer-personal-website",
  },
  {
      title: "Best Platforms for Building Your Website in 2024",
      date: "2024-03-05",
      category: "Tools",
      description: "Comparing the top platforms for website creation, including WordPress, Wix, and Squarespace. Learn which platform suits your needs, whether you’re a small business owner or a freelancer.",
      technologies: ["WordPress", "Squarespace", "Wix", "Web Development"],
      readTime: "8 min",
      link: "https://www.example.com/best-website-builders",
  },
  {
      title: "Building Your First Fiverr Gig Portfolio Website",
      date: "2024-03-01",
      category: "Freelancing",
      description: "A step-by-step guide to building a Fiverr portfolio website. Learn how to integrate your gigs, attract clients, and build trust with a professional online presence.",
      technologies: ["Fiverr", "Portfolio Websites", "Web Development"],
      readTime: "9 min",
      link: "https://www.example.com/fiverr-portfolio-guide",
  },
  {
      title: "10 Must-Have Features for a Small Business Website",
      date: "2024-02-28",
      category: "Business",
      description: "Ensure your website includes these essential features to engage customers and boost your business. From contact forms to SEO optimization, make your site work for you.",
      technologies: ["Web Design", "SEO", "User Experience"],
      readTime: "6 min",
      link: "https://www.example.com/small-business-website-features",
  },
  {
      title: "Creating SEO-Friendly Websites: A Beginner’s Guide",
      date: "2024-02-20",
      category: "SEO",
      description: "Learn the basics of SEO and how to create a website that ranks well on Google. Perfect for freelancers and business owners looking to increase online visibility.",
      technologies: ["SEO", "Web Development", "Google Analytics"],
      readTime: "7 min",
      link: "https://www.example.com/seo-friendly-website",
  },
  {
      title: "Freelance Web Development: Tips for Landing Your First Client",
      date: "2024-02-15",
      category: "Freelancing",
      description: "Breaking into freelance web development can be challenging. This guide covers strategies to find clients, set pricing, and showcase your work effectively.",
      technologies: ["Freelancing", "Web Development", "Marketing"],
      readTime: "8 min",
      link: "https://www.example.com/freelance-web-development-tips",
  }
];
